### ISSUE TITLE
Twitter reports: "DCC_RI_PIN_MISMATCH" error when attempting to reissue certificates

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#65]
Hey, there are some users reporting that the reissuing of their certificate does not work and the app displays the error "DCC_RI_PIN_MISMATCH". Are you aware of this? When will this be fixed?

**Comment by thomasaugsten** [comment]
We aware of this problem for iOS it should already be resolved. For android we waiting for the Google review. Which is expect tomorrow afternoon

**Comment by mlenkeit** [comment]
> Okay, so the iOS fix is [corona-warn-app/cwa-app-ios#4399](https://github.com/corona-warn-app/cwa-app-ios/pull/4399) & Android fix is [corona-warn-app/cwa-app-android#5005](https://github.com/corona-warn-app/cwa-app-android/pull/5005).

... and there's https://github.com/corona-warn-app/cwa-app-ios/pull/4403, https://github.com/corona-warn-app/cwa-app-android/pull/5011/files, and https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v2.0.0 to ensure that the problem doesn't hit devices on 2.19.

**Comment by Ein-Tim** [comment]
@mlenkeit 

> corona-warn-app/cwa-app-ios#4403, corona-warn-app/cwa-app-android#5011

What are these PRs actually doing? Preparing for version 2.0 of CCL?

**Comment by mlenkeit** [comment]
They basically ensure that CCL 1.x reaches CWA <= 2.19 and CCL 2.x reaches CWA >= 2.20. Otherwise - and because the wrong URL was already in 2.19 - if we enabled DCC reissuance in CCL 1.x, all users on 2.19 would still get the error message `DCC_RI_PIN_MISMATCH`.

**Comment by mlenkeit** [comment]
All fixes are deployed (CCL) or released as staged roll out (apps), so the error should disappear.

**Comment by MikeMcC399** [comment]
@mlenkeit 

I'm seeing CCL Version: 1.2.1 on a clean install of CWA Android 2.19.2 and I assume that this is correct, to ensure that DCC reissuance is not enabled.

**Comment by Ein-Tim** [comment]
Closing as fixed.

**Comment by mlenkeit** [comment]
> @mlenkeit
> 
> I'm seeing CCL Version: 1.2.1 on a clean install of CWA Android 2.19.2 and I assume that this is correct, to ensure that DCC reissuance is not enabled.

@MikeMcC399 exactly. CCL 2.0.0 (which has reissuance enabled) will only reach CWA 2.20.3.

**Comment by MikeMcC399** [comment]
- CWA Android 2.20.3 update from 2.19.2 currently showing CCL Version: 1.2.1
- CWA Android 2.20.3 clean install shows CCL Version: 2.0.0

This is expected. I further expect the updated app to update itself at the latest in 24 hours so that it also shows CCL 2.0.0 tomorrow.
